package selenium;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.support.ui.Select;

public class Adactin {
	public static void main(String[] args) {
		System.setProperty("webdriver.chrome.driver", "C:\\Users\\Sarvan\\eclipse-workspace\\Manojdurairaj\\selenium\\driver\\chromedriver.exe");
		WebDriver m=new ChromeDriver();
		//m.get("https://www.adactin.com/HotelApp/index.php");
        m.get("https://www.adactin.com/HotelApp/Register.php");
		WebElement abi = m.findElement(By.name("username"));
		abi.sendKeys("manojdurairaj");
		WebElement pwd = m.findElement(By.id("password"));
		pwd.sendKeys("mythili@10");
		WebElement pwd1 = m.findElement(By.id("re_password"));
		pwd1.sendKeys("mythili@10");
		WebElement fname = m.findElement(By.name("full_name"));
		fname.sendKeys("Manoj Durairaj");
		WebElement email = m.findElement(By.name("email_add"));
		email.sendKeys("manojdurairaj10@gmail.com");
		WebElement cpt = m.findElement(By.name("captcha"));
		cpt.sendKeys("maNoj");
		m.findElement(By.name("tnc_box")).click();
		//System.out.println(checkbox.isselected);
		m.findElement(By.name("Submit")).click();
		m.get("https://www.adactin.com/HotelApp/index.php");
		WebElement uname = m.findElement(By.name("username"));
		uname.sendKeys("manojdurairaj");
		WebElement pass = m.findElement(By.id("password"));
		pass.sendKeys("mythili@10");
		m.findElement(By.name("login")).click();
		WebElement loc = m.findElement(By.name("location"));
		Select s= new Select(loc);
		s.selectByValue("London");
		WebElement hot = m.findElement(By.name("hotels"));
		Select s1= new Select(hot);
		s1.selectByValue("Hotel Creek");
		WebElement room = m.findElement(By.name("room_type"));
		Select s2= new Select(room);
		s2.selectByValue("Deluxe");
		WebElement nos = m.findElement(By.name("room_nos"));
		Select s3=new Select(nos);
		s3.selectByValue("2");
		WebElement in = m.findElement(By.name("datepick_in"));
		in.sendKeys("28/12/2019");
		WebElement out = m.findElement(By.name("datepick_out"));
		out.sendKeys("30/12/2019");
		WebElement adl = m.findElement(By.name("adult_room"));
		Select s4= new Select(adl);
		s4.selectByValue("3");
		WebElement chl = m.findElement(By.name("child_room"));
		Select s5=new Select(chl);
		s5.selectByValue("2");
		m.findElement(By.xpath("//input[@name='Submit']")).click();
		m.findElement(By.name("radiobutton_0")).click();
		m.findElement(By.name("continue")).click();
		WebElement finame = m.findElement(By.name("first_name"));
		finame.sendKeys("Manoj");
		WebElement laname = m.findElement(By.name("last_name"));
		laname.sendKeys("prabhakar");
		WebElement addr = m.findElement(By.name("address"));
		addr.sendKeys("no.123, anna st,UK");
		WebElement cc = m.findElement(By.name("cc_num"));
		cc.sendKeys("9652231456987458"); 
		WebElement type = m.findElement(By.name("cc_type"));
		Select s6= new Select(type);
		s6.selectByValue("VISA");
		WebElement exp = m.findElement(By.name("cc_exp_month"));
		Select s7=new Select(exp);
		s7.selectByValue("3");
		WebElement ccc = m.findElement(By.name("cc_exp_year"));
		Select s8=new Select(ccc);
		s8.selectByValue("2013");
		WebElement cvv = m.findElement(By.name("cc_cvv"));
		cvv.sendKeys("321");
		m.findElement(By.xpath("//input[@type='button'][1]")).click();
		//m.quit(5J033R3R91);
	}
}
